// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AssignRoleEp } from '../src/api/assignRole';
import type { default as _BulkUpdateProductsEp } from '../src/api/bulkUpdateProducts';
import type { default as _CreateExpenseEp } from '../src/api/createExpense';
import type { default as _CreatePurchaseEp } from '../src/api/createPurchase';
import type { default as _CreateSaleEp } from '../src/api/createSale';
import type { default as _DeleteRecordEp } from '../src/api/deleteRecord';
import type { default as _ExportCsvEp } from '../src/api/exportCsv';
import type { default as _ExportLpoCsvEp } from '../src/api/exportLpoCsv';
import type { default as _GenerateLpoPdfEp } from '../src/api/generateLpoPdf';
import type { default as _GetAddressesEp } from '../src/api/getAddresses';
import type { default as _GetCategoriesEp } from '../src/api/getCategories';
import type { default as _GetCustomerDetailsEp } from '../src/api/getCustomerDetails';
import type { default as _GetCustomersEp } from '../src/api/getCustomers';
import type { default as _GetDashboardEp } from '../src/api/getDashboard';
import type { default as _GetExpensesEp } from '../src/api/getExpenses';
import type { default as _GetMyPermissionsEp } from '../src/api/getMyPermissions';
import type { default as _GetProductsEp } from '../src/api/getProducts';
import type { default as _GetPurchaseOrdersEp } from '../src/api/getPurchaseOrders';
import type { default as _GetPurchasesEp } from '../src/api/getPurchases';
import type { default as _GetRolesEp } from '../src/api/getRoles';
import type { default as _GetSalesEp } from '../src/api/getSales';
import type { default as _GetSettingsEp } from '../src/api/getSettings';
import type { default as _GetSupplierDetailsEp } from '../src/api/getSupplierDetails';
import type { default as _GetSuppliersEp } from '../src/api/getSuppliers';
import type { default as _GetUsersEp } from '../src/api/getUsers';
import type { default as _ImportCsvEp } from '../src/api/importCsv';
import type { default as _InviteUserEp } from '../src/api/inviteUser';
import type { default as _RecordDepositEp } from '../src/api/recordDeposit';
import type { default as _SaveAddressEp } from '../src/api/saveAddress';
import type { default as _SaveCategoryEp } from '../src/api/saveCategory';
import type { default as _SaveCustomerEp } from '../src/api/saveCustomer';
import type { default as _SaveProductEp } from '../src/api/saveProduct';
import type { default as _SavePurchaseOrderEp } from '../src/api/savePurchaseOrder';
import type { default as _SaveRoleEp } from '../src/api/saveRole';
import type { default as _SaveSettingsEp } from '../src/api/saveSettings';
import type { default as _SaveSupplierEp } from '../src/api/saveSupplier';
import type { default as _VerifyPurchaseOrderEp } from '../src/api/verifyPurchaseOrder';

type _AssignRoleCfg = typeof _AssignRoleEp;
export type AssignRoleInputType = NonNullable<_AssignRoleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AssignRoleCfg['execute']>[0]['input'];
export type AssignRoleOutputType = Awaited<ReturnType<_AssignRoleCfg['execute']>>;
export const assignRole = createCaller<AssignRoleInputType, AssignRoleOutputType>('assignRole');

type _BulkUpdateProductsCfg = typeof _BulkUpdateProductsEp;
export type BulkUpdateProductsInputType = NonNullable<_BulkUpdateProductsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BulkUpdateProductsCfg['execute']>[0]['input'];
export type BulkUpdateProductsOutputType = Awaited<ReturnType<_BulkUpdateProductsCfg['execute']>>;
export const bulkUpdateProducts = createCaller<BulkUpdateProductsInputType, BulkUpdateProductsOutputType>('bulkUpdateProducts');

type _CreateExpenseCfg = typeof _CreateExpenseEp;
export type CreateExpenseInputType = NonNullable<_CreateExpenseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateExpenseCfg['execute']>[0]['input'];
export type CreateExpenseOutputType = Awaited<ReturnType<_CreateExpenseCfg['execute']>>;
export const createExpense = createCaller<CreateExpenseInputType, CreateExpenseOutputType>('createExpense');

type _CreatePurchaseCfg = typeof _CreatePurchaseEp;
export type CreatePurchaseInputType = NonNullable<_CreatePurchaseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreatePurchaseCfg['execute']>[0]['input'];
export type CreatePurchaseOutputType = Awaited<ReturnType<_CreatePurchaseCfg['execute']>>;
export const createPurchase = createCaller<CreatePurchaseInputType, CreatePurchaseOutputType>('createPurchase');

type _CreateSaleCfg = typeof _CreateSaleEp;
export type CreateSaleInputType = NonNullable<_CreateSaleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateSaleCfg['execute']>[0]['input'];
export type CreateSaleOutputType = Awaited<ReturnType<_CreateSaleCfg['execute']>>;
export const createSale = createCaller<CreateSaleInputType, CreateSaleOutputType>('createSale');

type _DeleteRecordCfg = typeof _DeleteRecordEp;
export type DeleteRecordInputType = NonNullable<_DeleteRecordCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteRecordCfg['execute']>[0]['input'];
export type DeleteRecordOutputType = Awaited<ReturnType<_DeleteRecordCfg['execute']>>;
export const deleteRecord = createCaller<DeleteRecordInputType, DeleteRecordOutputType>('deleteRecord');

type _ExportCsvCfg = typeof _ExportCsvEp;
export type ExportCsvInputType = NonNullable<_ExportCsvCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportCsvCfg['execute']>[0]['input'];
export type ExportCsvOutputType = Awaited<ReturnType<_ExportCsvCfg['execute']>>;
export const exportCsv = createCaller<ExportCsvInputType, ExportCsvOutputType>('exportCsv');

type _ExportLpoCsvCfg = typeof _ExportLpoCsvEp;
export type ExportLpoCsvInputType = NonNullable<_ExportLpoCsvCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportLpoCsvCfg['execute']>[0]['input'];
export type ExportLpoCsvOutputType = Awaited<ReturnType<_ExportLpoCsvCfg['execute']>>;
export const exportLpoCsv = createCaller<ExportLpoCsvInputType, ExportLpoCsvOutputType>('exportLpoCsv');

type _GenerateLpoPdfCfg = typeof _GenerateLpoPdfEp;
export type GenerateLpoPdfInputType = NonNullable<_GenerateLpoPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateLpoPdfCfg['execute']>[0]['input'];
export type GenerateLpoPdfOutputType = Awaited<ReturnType<_GenerateLpoPdfCfg['execute']>>;
export const generateLpoPdf = createCaller<GenerateLpoPdfInputType, GenerateLpoPdfOutputType>('generateLpoPdf');

type _GetAddressesCfg = typeof _GetAddressesEp;
export type GetAddressesInputType = NonNullable<_GetAddressesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAddressesCfg['execute']>[0]['input'];
export type GetAddressesOutputType = Awaited<ReturnType<_GetAddressesCfg['execute']>>;
export const getAddresses = createCaller<GetAddressesInputType, GetAddressesOutputType>('getAddresses');

type _GetCategoriesCfg = typeof _GetCategoriesEp;
export type GetCategoriesInputType = NonNullable<_GetCategoriesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCategoriesCfg['execute']>[0]['input'];
export type GetCategoriesOutputType = Awaited<ReturnType<_GetCategoriesCfg['execute']>>;
export const getCategories = createCaller<GetCategoriesInputType, GetCategoriesOutputType>('getCategories');

type _GetCustomerDetailsCfg = typeof _GetCustomerDetailsEp;
export type GetCustomerDetailsInputType = NonNullable<_GetCustomerDetailsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCustomerDetailsCfg['execute']>[0]['input'];
export type GetCustomerDetailsOutputType = Awaited<ReturnType<_GetCustomerDetailsCfg['execute']>>;
export const getCustomerDetails = createCaller<GetCustomerDetailsInputType, GetCustomerDetailsOutputType>('getCustomerDetails');

type _GetCustomersCfg = typeof _GetCustomersEp;
export type GetCustomersInputType = NonNullable<_GetCustomersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCustomersCfg['execute']>[0]['input'];
export type GetCustomersOutputType = Awaited<ReturnType<_GetCustomersCfg['execute']>>;
export const getCustomers = createCaller<GetCustomersInputType, GetCustomersOutputType>('getCustomers');

type _GetDashboardCfg = typeof _GetDashboardEp;
export type GetDashboardInputType = NonNullable<_GetDashboardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetDashboardCfg['execute']>[0]['input'];
export type GetDashboardOutputType = Awaited<ReturnType<_GetDashboardCfg['execute']>>;
export const getDashboard = createCaller<GetDashboardInputType, GetDashboardOutputType>('getDashboard');

type _GetExpensesCfg = typeof _GetExpensesEp;
export type GetExpensesInputType = NonNullable<_GetExpensesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetExpensesCfg['execute']>[0]['input'];
export type GetExpensesOutputType = Awaited<ReturnType<_GetExpensesCfg['execute']>>;
export const getExpenses = createCaller<GetExpensesInputType, GetExpensesOutputType>('getExpenses');

type _GetMyPermissionsCfg = typeof _GetMyPermissionsEp;
export type GetMyPermissionsInputType = NonNullable<_GetMyPermissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMyPermissionsCfg['execute']>[0]['input'];
export type GetMyPermissionsOutputType = Awaited<ReturnType<_GetMyPermissionsCfg['execute']>>;
export const getMyPermissions = createCaller<GetMyPermissionsInputType, GetMyPermissionsOutputType>('getMyPermissions');

type _GetProductsCfg = typeof _GetProductsEp;
export type GetProductsInputType = NonNullable<_GetProductsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProductsCfg['execute']>[0]['input'];
export type GetProductsOutputType = Awaited<ReturnType<_GetProductsCfg['execute']>>;
export const getProducts = createCaller<GetProductsInputType, GetProductsOutputType>('getProducts');

type _GetPurchaseOrdersCfg = typeof _GetPurchaseOrdersEp;
export type GetPurchaseOrdersInputType = NonNullable<_GetPurchaseOrdersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPurchaseOrdersCfg['execute']>[0]['input'];
export type GetPurchaseOrdersOutputType = Awaited<ReturnType<_GetPurchaseOrdersCfg['execute']>>;
export const getPurchaseOrders = createCaller<GetPurchaseOrdersInputType, GetPurchaseOrdersOutputType>('getPurchaseOrders');

type _GetPurchasesCfg = typeof _GetPurchasesEp;
export type GetPurchasesInputType = NonNullable<_GetPurchasesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPurchasesCfg['execute']>[0]['input'];
export type GetPurchasesOutputType = Awaited<ReturnType<_GetPurchasesCfg['execute']>>;
export const getPurchases = createCaller<GetPurchasesInputType, GetPurchasesOutputType>('getPurchases');

type _GetRolesCfg = typeof _GetRolesEp;
export type GetRolesInputType = NonNullable<_GetRolesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetRolesCfg['execute']>[0]['input'];
export type GetRolesOutputType = Awaited<ReturnType<_GetRolesCfg['execute']>>;
export const getRoles = createCaller<GetRolesInputType, GetRolesOutputType>('getRoles');

type _GetSalesCfg = typeof _GetSalesEp;
export type GetSalesInputType = NonNullable<_GetSalesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSalesCfg['execute']>[0]['input'];
export type GetSalesOutputType = Awaited<ReturnType<_GetSalesCfg['execute']>>;
export const getSales = createCaller<GetSalesInputType, GetSalesOutputType>('getSales');

type _GetSettingsCfg = typeof _GetSettingsEp;
export type GetSettingsInputType = NonNullable<_GetSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSettingsCfg['execute']>[0]['input'];
export type GetSettingsOutputType = Awaited<ReturnType<_GetSettingsCfg['execute']>>;
export const getSettings = createCaller<GetSettingsInputType, GetSettingsOutputType>('getSettings');

type _GetSupplierDetailsCfg = typeof _GetSupplierDetailsEp;
export type GetSupplierDetailsInputType = NonNullable<_GetSupplierDetailsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSupplierDetailsCfg['execute']>[0]['input'];
export type GetSupplierDetailsOutputType = Awaited<ReturnType<_GetSupplierDetailsCfg['execute']>>;
export const getSupplierDetails = createCaller<GetSupplierDetailsInputType, GetSupplierDetailsOutputType>('getSupplierDetails');

type _GetSuppliersCfg = typeof _GetSuppliersEp;
export type GetSuppliersInputType = NonNullable<_GetSuppliersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSuppliersCfg['execute']>[0]['input'];
export type GetSuppliersOutputType = Awaited<ReturnType<_GetSuppliersCfg['execute']>>;
export const getSuppliers = createCaller<GetSuppliersInputType, GetSuppliersOutputType>('getSuppliers');

type _GetUsersCfg = typeof _GetUsersEp;
export type GetUsersInputType = NonNullable<_GetUsersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetUsersCfg['execute']>[0]['input'];
export type GetUsersOutputType = Awaited<ReturnType<_GetUsersCfg['execute']>>;
export const getUsers = createCaller<GetUsersInputType, GetUsersOutputType>('getUsers');

type _ImportCsvCfg = typeof _ImportCsvEp;
export type ImportCsvInputType = NonNullable<_ImportCsvCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ImportCsvCfg['execute']>[0]['input'];
export type ImportCsvOutputType = Awaited<ReturnType<_ImportCsvCfg['execute']>>;
export const importCsv = createCaller<ImportCsvInputType, ImportCsvOutputType>('importCsv');

type _InviteUserCfg = typeof _InviteUserEp;
export type InviteUserInputType = NonNullable<_InviteUserCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_InviteUserCfg['execute']>[0]['input'];
export type InviteUserOutputType = Awaited<ReturnType<_InviteUserCfg['execute']>>;
export const inviteUser = createCaller<InviteUserInputType, InviteUserOutputType>('inviteUser');

type _RecordDepositCfg = typeof _RecordDepositEp;
export type RecordDepositInputType = NonNullable<_RecordDepositCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RecordDepositCfg['execute']>[0]['input'];
export type RecordDepositOutputType = Awaited<ReturnType<_RecordDepositCfg['execute']>>;
export const recordDeposit = createCaller<RecordDepositInputType, RecordDepositOutputType>('recordDeposit');

type _SaveAddressCfg = typeof _SaveAddressEp;
export type SaveAddressInputType = NonNullable<_SaveAddressCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAddressCfg['execute']>[0]['input'];
export type SaveAddressOutputType = Awaited<ReturnType<_SaveAddressCfg['execute']>>;
export const saveAddress = createCaller<SaveAddressInputType, SaveAddressOutputType>('saveAddress');

type _SaveCategoryCfg = typeof _SaveCategoryEp;
export type SaveCategoryInputType = NonNullable<_SaveCategoryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCategoryCfg['execute']>[0]['input'];
export type SaveCategoryOutputType = Awaited<ReturnType<_SaveCategoryCfg['execute']>>;
export const saveCategory = createCaller<SaveCategoryInputType, SaveCategoryOutputType>('saveCategory');

type _SaveCustomerCfg = typeof _SaveCustomerEp;
export type SaveCustomerInputType = NonNullable<_SaveCustomerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCustomerCfg['execute']>[0]['input'];
export type SaveCustomerOutputType = Awaited<ReturnType<_SaveCustomerCfg['execute']>>;
export const saveCustomer = createCaller<SaveCustomerInputType, SaveCustomerOutputType>('saveCustomer');

type _SaveProductCfg = typeof _SaveProductEp;
export type SaveProductInputType = NonNullable<_SaveProductCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProductCfg['execute']>[0]['input'];
export type SaveProductOutputType = Awaited<ReturnType<_SaveProductCfg['execute']>>;
export const saveProduct = createCaller<SaveProductInputType, SaveProductOutputType>('saveProduct');

type _SavePurchaseOrderCfg = typeof _SavePurchaseOrderEp;
export type SavePurchaseOrderInputType = NonNullable<_SavePurchaseOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePurchaseOrderCfg['execute']>[0]['input'];
export type SavePurchaseOrderOutputType = Awaited<ReturnType<_SavePurchaseOrderCfg['execute']>>;
export const savePurchaseOrder = createCaller<SavePurchaseOrderInputType, SavePurchaseOrderOutputType>('savePurchaseOrder');

type _SaveRoleCfg = typeof _SaveRoleEp;
export type SaveRoleInputType = NonNullable<_SaveRoleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveRoleCfg['execute']>[0]['input'];
export type SaveRoleOutputType = Awaited<ReturnType<_SaveRoleCfg['execute']>>;
export const saveRole = createCaller<SaveRoleInputType, SaveRoleOutputType>('saveRole');

type _SaveSettingsCfg = typeof _SaveSettingsEp;
export type SaveSettingsInputType = NonNullable<_SaveSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSettingsCfg['execute']>[0]['input'];
export type SaveSettingsOutputType = Awaited<ReturnType<_SaveSettingsCfg['execute']>>;
export const saveSettings = createCaller<SaveSettingsInputType, SaveSettingsOutputType>('saveSettings');

type _SaveSupplierCfg = typeof _SaveSupplierEp;
export type SaveSupplierInputType = NonNullable<_SaveSupplierCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSupplierCfg['execute']>[0]['input'];
export type SaveSupplierOutputType = Awaited<ReturnType<_SaveSupplierCfg['execute']>>;
export const saveSupplier = createCaller<SaveSupplierInputType, SaveSupplierOutputType>('saveSupplier');

type _VerifyPurchaseOrderCfg = typeof _VerifyPurchaseOrderEp;
export type VerifyPurchaseOrderInputType = NonNullable<_VerifyPurchaseOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_VerifyPurchaseOrderCfg['execute']>[0]['input'];
export type VerifyPurchaseOrderOutputType = Awaited<ReturnType<_VerifyPurchaseOrderCfg['execute']>>;
export const verifyPurchaseOrder = createCaller<VerifyPurchaseOrderInputType, VerifyPurchaseOrderOutputType>('verifyPurchaseOrder');


export const api = {
  assignRole,
  bulkUpdateProducts,
  createExpense,
  createPurchase,
  createSale,
  deleteRecord,
  exportCsv,
  exportLpoCsv,
  generateLpoPdf,
  getAddresses,
  getCategories,
  getCustomerDetails,
  getCustomers,
  getDashboard,
  getExpenses,
  getMyPermissions,
  getProducts,
  getPurchaseOrders,
  getPurchases,
  getRoles,
  getSales,
  getSettings,
  getSupplierDetails,
  getSuppliers,
  getUsers,
  importCsv,
  inviteUser,
  recordDeposit,
  saveAddress,
  saveCategory,
  saveCustomer,
  saveProduct,
  savePurchaseOrder,
  saveRole,
  saveSettings,
  saveSupplier,
  verifyPurchaseOrder,
};
