// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
//
// Link tables for zite.sql() JOINs (use these exact names):
//   "CategoriesProducts" — columns: "categoriesId", "productsId" (joins "Categories" and "Products")
//   "BranchesProducts" — columns: "branchesId", "productsId" (joins "Branches" and "Products")
//   "ProductVariationsProducts" — columns: "productVariationsId", "productsId" (joins "Product Variations" and "Products")
//   "ProductSuppliersProducts" — columns: "productSuppliersId", "productsId" (joins "Product Suppliers" and "Products")
//   "ProductSuppliersSuppliers" — columns: "productSuppliersId", "suppliersId" (joins "Product Suppliers" and "Suppliers")
//   "SupplierDepositsSuppliers" — columns: "supplierDepositsId", "suppliersId" (joins "Supplier Deposits" and "Suppliers")
//   "BranchesSupplierDeposits" — columns: "branchesId", "supplierDepositsId" (joins "Branches" and "Supplier Deposits")
//   "CustomersSales" — columns: "customersId", "salesId" (joins "Customers" and "Sales")
//   "BranchesSales" — columns: "branchesId", "salesId" (joins "Branches" and "Sales")
//   "SaleItemsSales" — columns: "saleItemsId", "salesId" (joins "Sale Items" and "Sales")
//   "ProductsSaleItems" — columns: "productsId", "saleItemsId" (joins "Products" and "Sale Items")
//   "PurchasesSuppliers" — columns: "purchasesId", "suppliersId" (joins "Purchases" and "Suppliers")
//   "BranchesPurchases" — columns: "branchesId", "purchasesId" (joins "Branches" and "Purchases")
//   "PurchaseItemsPurchases" — columns: "purchaseItemsId", "purchasesId" (joins "Purchase Items" and "Purchases")
//   "ProductsPurchaseItems" — columns: "productsId", "purchaseItemsId" (joins "Products" and "Purchase Items")
//   "ExpenseCategoriesOtherExpenses" — columns: "expenseCategoriesId", "otherExpensesId" (joins "Expense Categories" and "Other Expenses")
//   "BranchesOtherExpenses" — columns: "branchesId", "otherExpensesId" (joins "Branches" and "Other Expenses")
//   "BranchesOtherIncome" — columns: "branchesId", "otherIncomeId" (joins "Branches" and "Other Income")
//   "SupplierTransactionsSuppliers" — columns: "supplierTransactionsId", "suppliersId" (joins "Supplier Transactions" and "Suppliers")
//   "ProductsSupplierTransactions" — columns: "productsId", "supplierTransactionsId" (joins "Products" and "Supplier Transactions")
//   "PurchaseOrdersSuppliers" — columns: "purchaseOrdersId", "suppliersId" (joins "Purchase Orders" and "Suppliers")
//   "BranchesPurchaseOrders" — columns: "branchesId", "purchaseOrdersId" (joins "Branches" and "Purchase Orders")
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Business Settings" table, as it is read back. */
export type BusinessSettingsRecordType = {
  id: string;
  /** Primary field. "Business Name" */
  businessName?: string;
  logo?: ZiteAttachment[];
  coverPhoto?: ZiteAttachment[];
  address?: string;
  phone?: string;
  email?: string;
  taxId?: string;
  customFields?: string;
  defaultCurrency?: string;
};

/** What you may write when creating or updating a record in the "Business Settings" table. */
export type BusinessSettingsRecordInput = {
  businessName: string | null;
  logo: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  coverPhoto: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  taxId: string | null;
  customFields: string | null;
  defaultCurrency: string | null;
};

/** A record in the "Branches" table, as it is read back. */
export type BranchesRecordType = {
  id: string;
  /** Primary field. "Branch Name" */
  branchName?: string;
  address?: string;
  phone?: string;
  taxId?: string;
  customFields?: string;
  isMainBranch?: boolean;
  active?: boolean;
  /** Links to products ("Products"). "Products" */
  products?: string | string[];
  /** Links to supplierDeposits ("Supplier Deposits"). "Supplier Deposits" */
  supplierDeposits?: string | string[];
  /** Links to sales ("Sales"). "Sales" */
  sales?: string | string[];
  /** Links to purchases ("Purchases"). "Purchases" */
  purchases?: string | string[];
  /** Links to otherExpenses ("Other Expenses"). "Other Expenses" */
  otherExpenses?: string | string[];
  /** Links to otherIncome ("Other Income"). "Other Income" */
  otherIncome?: string | string[];
  /** Links to purchaseOrders ("Purchase Orders"). "Purchase Orders" */
  purchaseOrders?: string | string[];
  plusCode?: string;
  coordinates?: string;
};

/** What you may write when creating or updating a record in the "Branches" table. */
export type BranchesRecordInput = {
  branchName: string | null;
  address: string | null;
  phone: string | null;
  taxId: string | null;
  customFields: string | null;
  isMainBranch: string | boolean | null;
  active: string | boolean | null;
  products: string | string[] | null;
  supplierDeposits: string | string[] | null;
  sales: string | string[] | null;
  purchases: string | string[] | null;
  otherExpenses: string | string[] | null;
  otherIncome: string | string[] | null;
  purchaseOrders: string | string[] | null;
  plusCode: string | null;
  coordinates: string | null;
};

/** A record in the "Currencies" table, as it is read back. */
export type CurrenciesRecordType = {
  id: string;
  /** Primary field. "Currency Code" */
  currencyCode?: string;
  symbol?: string;
  /** "Exchange Rate". 4 decimal places, format: local (e.g. 1,000,000.50) */
  exchangeRate?: number;
  isDefault?: boolean;
  active?: boolean;
};

/** What you may write when creating or updating a record in the "Currencies" table. */
export type CurrenciesRecordInput = {
  currencyCode: string | null;
  symbol: string | null;
  exchangeRate: string | number | null;
  isDefault: string | boolean | null;
  active: string | boolean | null;
};

/** A record in the "Categories" table, as it is read back. */
export type CategoriesRecordType = {
  id: string;
  /** Primary field. "Category Name" */
  categoryName?: string;
  description?: string;
  image?: ZiteAttachment[];
  active?: boolean;
  /** Links to products ("Products"). "Products" */
  products?: string | string[];
};

/** What you may write when creating or updating a record in the "Categories" table. */
export type CategoriesRecordInput = {
  categoryName: string | null;
  description: string | null;
  image: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  active: string | boolean | null;
  products: string | string[] | null;
};

/** A record in the "Products" table, as it is read back. */
export type ProductsRecordType = {
  id: string;
  /** Primary field. "Product Name" */
  productName?: string;
  sku?: string;
  /** "Cost Price". 2 decimal places, format: local (e.g. 1,000,000.50) */
  costPrice?: number;
  /** "Selling Price". 2 decimal places, format: local (e.g. 1,000,000.50) */
  sellingPrice?: number;
  /** Links to categories ("Categories"). "Category" */
  category?: string | string[];
  images?: ZiteAttachment[];
  status?: "Active" | "Inactive" | string;
  /** "Stock Quantity". 0 decimal places, format: local (e.g. 1,000,000.50) */
  stockQuantity?: number;
  /** "Reorder Level". 0 decimal places, format: local (e.g. 1,000,000.50) */
  reorderLevel?: number;
  /** "Tax Rate". 2 decimal places, format: local (e.g. 1,000,000.50) */
  taxRate?: number;
  description?: string;
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
  /** Links to productVariations ("Product Variations"). "Product Variations" */
  productVariations?: string | string[];
  /** Links to productSuppliers ("Product Suppliers"). "Product Suppliers" */
  productSuppliers?: string | string[];
  /** Links to saleItems ("Sale Items"). "Sale Items" */
  saleItems?: string | string[];
  /** Links to purchaseItems ("Purchase Items"). "Purchase Items" */
  purchaseItems?: string | string[];
  /** Links to supplierTransactions ("Supplier Transactions"). "Supplier Transactions" */
  supplierTransactions?: string | string[];
};

/** What you may write when creating or updating a record in the "Products" table. */
export type ProductsRecordInput = {
  productName: string | null;
  sku: string | null;
  costPrice: string | number | null;
  sellingPrice: string | number | null;
  category: string | string[] | null;
  images: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  status: "Active" | "Inactive" | string | null;
  stockQuantity: string | number | null;
  reorderLevel: string | number | null;
  taxRate: string | number | null;
  description: string | null;
  branch: string | string[] | null;
  productVariations: string | string[] | null;
  productSuppliers: string | string[] | null;
  saleItems: string | string[] | null;
  purchaseItems: string | string[] | null;
  supplierTransactions: string | string[] | null;
};

/** A record in the "Product Variations" table, as it is read back. */
export type ProductVariationsRecordType = {
  id: string;
  /** Primary field. "Variation Name" */
  variationName?: string;
  sku?: string;
  /** "Cost Price". 2 decimal places, format: local (e.g. 1,000,000.50) */
  costPrice?: number;
  /** "Selling Price". 2 decimal places, format: local (e.g. 1,000,000.50) */
  sellingPrice?: number;
  /** "Stock Quantity". 0 decimal places, format: local (e.g. 1,000,000.50) */
  stockQuantity?: number;
  /** Links to products ("Products"). "Product" */
  product?: string | string[];
};

/** What you may write when creating or updating a record in the "Product Variations" table. */
export type ProductVariationsRecordInput = {
  variationName: string | null;
  sku: string | null;
  costPrice: string | number | null;
  sellingPrice: string | number | null;
  stockQuantity: string | number | null;
  product: string | string[] | null;
};

/** A record in the "Customers" table, as it is read back. */
export type CustomersRecordType = {
  id: string;
  /** Primary field. "Phone Number" */
  phoneNumber?: string;
  customerName?: string;
  email?: string;
  address?: string;
  notes?: string;
  /** Links to sales ("Sales"). "Sales" */
  sales?: string | string[];
  location?: string;
  coordinates?: string;
  plusCode?: string;
};

/** What you may write when creating or updating a record in the "Customers" table. */
export type CustomersRecordInput = {
  phoneNumber: string | null;
  customerName: string | null;
  email: string | null;
  address: string | null;
  notes: string | null;
  sales: string | string[] | null;
  location: string | null;
  coordinates: string | null;
  plusCode: string | null;
};

/** A record in the "Suppliers" table, as it is read back. */
export type SuppliersRecordType = {
  id: string;
  /** Primary field. "Supplier Name" */
  supplierName?: string;
  phone?: string;
  email?: string;
  address?: string;
  /** "Deposit Balance". 2 decimal places, format: local (e.g. 1,000,000.50) */
  depositBalance?: number;
  notes?: string;
  /** Links to productSuppliers ("Product Suppliers"). "Product Suppliers" */
  productSuppliers?: string | string[];
  /** Links to supplierDeposits ("Supplier Deposits"). "Supplier Deposits" */
  supplierDeposits?: string | string[];
  /** Links to purchases ("Purchases"). "Purchases" */
  purchases?: string | string[];
  /** Links to supplierTransactions ("Supplier Transactions"). "Supplier Transactions" */
  supplierTransactions?: string | string[];
  /** Links to purchaseOrders ("Purchase Orders"). "Purchase Orders" */
  purchaseOrders?: string | string[];
};

/** What you may write when creating or updating a record in the "Suppliers" table. */
export type SuppliersRecordInput = {
  supplierName: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  depositBalance: string | number | null;
  notes: string | null;
  productSuppliers: string | string[] | null;
  supplierDeposits: string | string[] | null;
  purchases: string | string[] | null;
  supplierTransactions: string | string[] | null;
  purchaseOrders: string | string[] | null;
};

/** A record in the "Product Suppliers" table, as it is read back. */
export type ProductSuppliersRecordType = {
  id: string;
  /** Primary field. Read-only. "ID" */
  id2?: number;
  /** Links to products ("Products"). "Product" */
  product?: string | string[];
  /** Links to suppliers ("Suppliers"). "Supplier" */
  supplier?: string | string[];
};

/** What you may write when creating or updating a record in the "Product Suppliers" table. */
export type ProductSuppliersRecordInput = {
  product: string | string[] | null;
  supplier: string | string[] | null;
};

/** A record in the "Supplier Deposits" table, as it is read back. */
export type SupplierDepositsRecordType = {
  id: string;
  /** Primary field. Read-only. "Deposit Number" */
  depositNumber?: number;
  /** Links to suppliers ("Suppliers"). "Supplier" */
  supplier?: string | string[];
  /** "Amount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  notes?: string;
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
};

/** What you may write when creating or updating a record in the "Supplier Deposits" table. */
export type SupplierDepositsRecordInput = {
  supplier: string | string[] | null;
  amount: string | number | null;
  date: string | Date | null;
  notes: string | null;
  branch: string | string[] | null;
};

/** A record in the "Sales" table, as it is read back. */
export type SalesRecordType = {
  id: string;
  /** Primary field. Read-only. "Sale Number" */
  saleNumber?: number;
  /** "Sale Date". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  saleDate?: string;
  /** Links to customers ("Customers"). "Customer" */
  customer?: string | string[];
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
  paymentMethod?: "Cash" | "M-Pesa" | "Card" | "Bank Transfer" | string;
  /** "Subtotal". 2 decimal places, format: local (e.g. 1,000,000.50) */
  subtotal?: number;
  /** "Tax Amount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  taxAmount?: number;
  /** "Discount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  discount?: number;
  /** "Total". 2 decimal places, format: local (e.g. 1,000,000.50) */
  total?: number;
  status?: "Completed" | "Pending" | "Voided" | string;
  notes?: string;
  createdBy?: string | string[];
  /** Links to saleItems ("Sale Items"). "Sale Items" */
  saleItems?: string | string[];
  pickupPoint?: string;
  deliveryAddress?: string;
  deliveryCoordinates?: string;
  stops?: string;
  /** "Delivery Distance Km". 1 decimal places, format: local (e.g. 1,000,000.50) */
  deliveryDistanceKm?: number;
};

/** What you may write when creating or updating a record in the "Sales" table. */
export type SalesRecordInput = {
  saleDate: string | Date | null;
  customer: string | string[] | null;
  branch: string | string[] | null;
  paymentMethod: "Cash" | "M-Pesa" | "Card" | "Bank Transfer" | string | null;
  subtotal: string | number | null;
  taxAmount: string | number | null;
  discount: string | number | null;
  total: string | number | null;
  status: "Completed" | "Pending" | "Voided" | string | null;
  notes: string | null;
  createdBy: string | string[] | null;
  saleItems: string | string[] | null;
  pickupPoint: string | null;
  deliveryAddress: string | null;
  deliveryCoordinates: string | null;
  stops: string | null;
  deliveryDistanceKm: string | number | null;
};

/** A record in the "Sale Items" table, as it is read back. */
export type SaleItemsRecordType = {
  id: string;
  /** Primary field. Read-only. "Item Number" */
  itemNumber?: number;
  /** Links to sales ("Sales"). "Sale" */
  sale?: string | string[];
  /** Links to products ("Products"). "Product" */
  product?: string | string[];
  /** "Quantity". 0 decimal places, format: local (e.g. 1,000,000.50) */
  quantity?: number;
  /** "Unit Price". 2 decimal places, format: local (e.g. 1,000,000.50) */
  unitPrice?: number;
  /** "Tax Amount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  taxAmount?: number;
  /** "Discount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  discount?: number;
  /** "Line Total". 2 decimal places, format: local (e.g. 1,000,000.50) */
  lineTotal?: number;
};

/** What you may write when creating or updating a record in the "Sale Items" table. */
export type SaleItemsRecordInput = {
  sale: string | string[] | null;
  product: string | string[] | null;
  quantity: string | number | null;
  unitPrice: string | number | null;
  taxAmount: string | number | null;
  discount: string | number | null;
  lineTotal: string | number | null;
};

/** A record in the "Expense Categories" table, as it is read back. */
export type ExpenseCategoriesRecordType = {
  id: string;
  /** Primary field. "Category Name" */
  categoryName?: string;
  type?: "Purchase" | "Other Expense" | string;
  active?: boolean;
  /** Links to otherExpenses ("Other Expenses"). "Other Expenses" */
  otherExpenses?: string | string[];
};

/** What you may write when creating or updating a record in the "Expense Categories" table. */
export type ExpenseCategoriesRecordInput = {
  categoryName: string | null;
  type: "Purchase" | "Other Expense" | string | null;
  active: string | boolean | null;
  otherExpenses: string | string[] | null;
};

/** A record in the "Purchases" table, as it is read back. */
export type PurchasesRecordType = {
  id: string;
  /** Primary field. Read-only. "Purchase Number" */
  purchaseNumber?: number;
  /** "Purchase Date". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  purchaseDate?: string;
  /** Links to suppliers ("Suppliers"). "Supplier" */
  supplier?: string | string[];
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
  /** "Total". 2 decimal places, format: local (e.g. 1,000,000.50) */
  total?: number;
  paymentType?: "Cash" | "From Deposit" | string;
  notes?: string;
  createdBy?: string | string[];
  /** Links to purchaseItems ("Purchase Items"). "Purchase Items" */
  purchaseItems?: string | string[];
};

/** What you may write when creating or updating a record in the "Purchases" table. */
export type PurchasesRecordInput = {
  purchaseDate: string | Date | null;
  supplier: string | string[] | null;
  branch: string | string[] | null;
  total: string | number | null;
  paymentType: "Cash" | "From Deposit" | string | null;
  notes: string | null;
  createdBy: string | string[] | null;
  purchaseItems: string | string[] | null;
};

/** A record in the "Purchase Items" table, as it is read back. */
export type PurchaseItemsRecordType = {
  id: string;
  /** Primary field. Read-only. "Item Number" */
  itemNumber?: number;
  /** Links to purchases ("Purchases"). "Purchase" */
  purchase?: string | string[];
  /** Links to products ("Products"). "Product" */
  product?: string | string[];
  /** "Quantity". 0 decimal places, format: local (e.g. 1,000,000.50) */
  quantity?: number;
  /** "Unit Price". 2 decimal places, format: local (e.g. 1,000,000.50) */
  unitPrice?: number;
  /** "Line Total". 2 decimal places, format: local (e.g. 1,000,000.50) */
  lineTotal?: number;
};

/** What you may write when creating or updating a record in the "Purchase Items" table. */
export type PurchaseItemsRecordInput = {
  purchase: string | string[] | null;
  product: string | string[] | null;
  quantity: string | number | null;
  unitPrice: string | number | null;
  lineTotal: string | number | null;
};

/** A record in the "Other Expenses" table, as it is read back. */
export type OtherExpensesRecordType = {
  id: string;
  /** Primary field. Read-only. "Expense Number" */
  expenseNumber?: number;
  /** "Expense Date". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  expenseDate?: string;
  description?: string;
  /** "Amount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** Links to expenseCategories ("Expense Categories"). "Category" */
  category?: string | string[];
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
  notes?: string;
  createdBy?: string | string[];
};

/** What you may write when creating or updating a record in the "Other Expenses" table. */
export type OtherExpensesRecordInput = {
  expenseDate: string | Date | null;
  description: string | null;
  amount: string | number | null;
  category: string | string[] | null;
  branch: string | string[] | null;
  notes: string | null;
  createdBy: string | string[] | null;
};

/** A record in the "Other Income" table, as it is read back. */
export type OtherIncomeRecordType = {
  id: string;
  /** Primary field. Read-only. "Income Number" */
  incomeNumber?: number;
  /** "Income Date". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  incomeDate?: string;
  description?: string;
  /** "Amount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
  notes?: string;
  createdBy?: string | string[];
};

/** What you may write when creating or updating a record in the "Other Income" table. */
export type OtherIncomeRecordInput = {
  incomeDate: string | Date | null;
  description: string | null;
  amount: string | number | null;
  branch: string | string[] | null;
  notes: string | null;
  createdBy: string | string[] | null;
};

/** A record in the "Taxes" table, as it is read back. */
export type TaxesRecordType = {
  id: string;
  /** Primary field. "Tax Name" */
  taxName?: string;
  /** "Rate". 2 decimal places, format: local (e.g. 1,000,000.50) */
  rate?: number;
  inclusive?: boolean;
  active?: boolean;
};

/** What you may write when creating or updating a record in the "Taxes" table. */
export type TaxesRecordInput = {
  taxName: string | null;
  rate: string | number | null;
  inclusive: string | boolean | null;
  active: string | boolean | null;
};

/** A record in the "Commissions" table, as it is read back. */
export type CommissionsRecordType = {
  id: string;
  /** Primary field. "Commission Name" */
  commissionName?: string;
  /** "Rate". 2 decimal places, format: local (e.g. 1,000,000.50) */
  rate?: number;
  active?: boolean;
};

/** What you may write when creating or updating a record in the "Commissions" table. */
export type CommissionsRecordInput = {
  commissionName: string | null;
  rate: string | number | null;
  active: string | boolean | null;
};

/** A record in the "Supplier Transactions" table, as it is read back. */
export type SupplierTransactionsRecordType = {
  id: string;
  /** Primary field. Read-only. "Transaction Number" */
  transactionNumber?: number;
  /** Links to suppliers ("Suppliers"). "Supplier" */
  supplier?: string | string[];
  /** Links to products ("Products"). "Product" */
  product?: string | string[];
  type?: "Deposit" | "Purchase Deduction" | string;
  /** "Amount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** "Running Balance". 2 decimal places, format: local (e.g. 1,000,000.50) */
  runningBalance?: number;
  /** "Transaction Date". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  transactionDate?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Supplier Transactions" table. */
export type SupplierTransactionsRecordInput = {
  supplier: string | string[] | null;
  product: string | string[] | null;
  type: "Deposit" | "Purchase Deduction" | string | null;
  amount: string | number | null;
  runningBalance: string | number | null;
  transactionDate: string | Date | null;
  notes: string | null;
};

/** A record in the "Roles" table, as it is read back. */
export type RolesRecordType = {
  id: string;
  /** Primary field. "Role Name" */
  roleName?: string;
  description?: string;
  permissions?: string;
  isDefault?: boolean;
  active?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Read-only. "Updated At". Auto-set when record was last modified (ISO 8601) */
  updatedAt?: string;
};

/** What you may write when creating or updating a record in the "Roles" table. */
export type RolesRecordInput = {
  roleName: string | null;
  description: string | null;
  permissions: string | null;
  isDefault: string | boolean | null;
  active: string | boolean | null;
};

/** A record in the "Purchase Orders" table, as it is read back. */
export type PurchaseOrdersRecordType = {
  id: string;
  /** Primary field. "LPO Number" */
  lpoNumber?: string;
  /** Links to suppliers ("Suppliers"). "Supplier" */
  supplier?: string | string[];
  /** Links to branches ("Branches"). "Branch" */
  branch?: string | string[];
  /** "Order Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  orderDate?: string;
  /** "Expected Delivery Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  expectedDeliveryDate?: string;
  status?: "Draft" | "Sent" | "Partially Verified" | "Verified" | "Cancelled" | string;
  /** "Total Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  totalAmount?: number;
  notes?: string;
  itemsJson?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Read-only. "Updated At". Auto-set when record was last modified (ISO 8601) */
  updatedAt?: string;
};

/** What you may write when creating or updating a record in the "Purchase Orders" table. */
export type PurchaseOrdersRecordInput = {
  lpoNumber: string | null;
  supplier: string | string[] | null;
  branch: string | string[] | null;
  orderDate: string | Date | null;
  expectedDeliveryDate: string | Date | null;
  status: "Draft" | "Sent" | "Partially Verified" | "Verified" | "Cancelled" | string | null;
  totalAmount: string | number | null;
  notes: string | null;
  itemsJson: string | null;
};

/** A record in the "Addresses" table, as it is read back. */
export type AddressesRecordType = {
  id: string;
  /** Primary field. "Address Name" */
  addressName?: string;
  type?: "Pickup Point" | "Delivery Address" | "Branch" | "Other" | string;
  fullAddress?: string;
  plusCode?: string;
  coordinates?: string;
  notes?: string;
  active?: boolean;
};

/** What you may write when creating or updating a record in the "Addresses" table. */
export type AddressesRecordInput = {
  addressName: string | null;
  type: "Pickup Point" | "Delivery Address" | "Branch" | "Other" | string | null;
  fullAddress: string | null;
  plusCode: string | null;
  coordinates: string | null;
  notes: string | null;
  active: string | boolean | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  businessSettings: createTableClient<BusinessSettingsRecordType, BusinessSettingsRecordInput>('BusinessSettings'), // "Business Settings"
  branches: createTableClient<BranchesRecordType, BranchesRecordInput>('Branches'), // "Branches"
  currencies: createTableClient<CurrenciesRecordType, CurrenciesRecordInput>('Currencies'), // "Currencies"
  categories: createTableClient<CategoriesRecordType, CategoriesRecordInput>('Categories'), // "Categories"
  products: createTableClient<ProductsRecordType, ProductsRecordInput>('Products'), // "Products"
  productVariations: createTableClient<ProductVariationsRecordType, ProductVariationsRecordInput>('ProductVariations'), // "Product Variations"
  customers: createTableClient<CustomersRecordType, CustomersRecordInput>('Customers'), // "Customers"
  suppliers: createTableClient<SuppliersRecordType, SuppliersRecordInput>('Suppliers'), // "Suppliers"
  productSuppliers: createTableClient<ProductSuppliersRecordType, ProductSuppliersRecordInput>('ProductSuppliers'), // "Product Suppliers"
  supplierDeposits: createTableClient<SupplierDepositsRecordType, SupplierDepositsRecordInput>('SupplierDeposits'), // "Supplier Deposits"
  sales: createTableClient<SalesRecordType, SalesRecordInput>('Sales'), // "Sales"
  saleItems: createTableClient<SaleItemsRecordType, SaleItemsRecordInput>('SaleItems'), // "Sale Items"
  expenseCategories: createTableClient<ExpenseCategoriesRecordType, ExpenseCategoriesRecordInput>('ExpenseCategories'), // "Expense Categories"
  purchases: createTableClient<PurchasesRecordType, PurchasesRecordInput>('Purchases'), // "Purchases"
  purchaseItems: createTableClient<PurchaseItemsRecordType, PurchaseItemsRecordInput>('PurchaseItems'), // "Purchase Items"
  otherExpenses: createTableClient<OtherExpensesRecordType, OtherExpensesRecordInput>('OtherExpenses'), // "Other Expenses"
  otherIncome: createTableClient<OtherIncomeRecordType, OtherIncomeRecordInput>('OtherIncome'), // "Other Income"
  taxes: createTableClient<TaxesRecordType, TaxesRecordInput>('Taxes'), // "Taxes"
  commissions: createTableClient<CommissionsRecordType, CommissionsRecordInput>('Commissions'), // "Commissions"
  supplierTransactions: createTableClient<SupplierTransactionsRecordType, SupplierTransactionsRecordInput>('SupplierTransactions'), // "Supplier Transactions"
  roles: createTableClient<RolesRecordType, RolesRecordInput>('Roles'), // "Roles"
  purchaseOrders: createTableClient<PurchaseOrdersRecordType, PurchaseOrdersRecordInput>('PurchaseOrders'), // "Purchase Orders"
  addresses: createTableClient<AddressesRecordType, AddressesRecordInput>('Addresses'), // "Addresses"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
